spring.application.name=EveryDayHelp

# import secret file
spring.config.import=optional:classpath:application-secret.properties


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# for limiting the file upload size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
#max-file-size: Maximum size of a single uploaded file
#max-request-size: Total size of multipart/form-data request

#app.upload.dir=upload

#change app logo
spring.banner.location=classpath:logo.ascii

#
app.title=Daily-Help-Portal
app.address =Noida-CyberCIty ,Uttat Pradesh
app.phone=2343234345



